### ISSUE TITLE
Blast code still failing

### ISSUE THREAD

**Issue by ChrisMantegna** [course-fish546-2023/chris-coursework1#2]
My blast code is still failing here, citing too long of a file name and then quits: 
`curl -O -H "Accept: text/plain; format=tsv" "https://rest.uniprot.org/uniprotkb/stream?compressed=true&fields=accession%2Creviewed%2Cid%2Cprotein_name%2Cgene_names%2Corganism_name%2Clength%2Cgo_f%2Cgo%2Cgo_p%2Cgo_c%2Cgo_id%2Ccc_interaction%2Cec%2Cxref_reactome%2Cxref_unipathway%2Cxref_interpro&format=tsv&query=%28%2A%29%20AND%20%28reviewed%3Atrue%29"`

How do I fix that?

**Comment by sr320** [comment]
This is curl not blast.... can you put a link to file in question? (code ie Rmd file)

**Comment by ChrisMantegna** [comment]
Sorry, I actually meant bash... the code is [here](assignment-code/01-blast.rmd) starting at line 72

**Comment by sr320** [comment]
That is likely an API issue (if you remember from class)...

This is the means to get that information I believe: https://github.com/course-fish546-2023/steven-coursework/blob/7ce09badbea8fa3683b90f9d9e1db36e8a41ea35/assignments/code/01-blast.Rmd#L105
